[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "forge-zksync-std/=lib/forge-zksync-std/src/",
]
solc_version = "0.8.28"
evm_version = "cancun"
auto_detect_solc = false
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100 # While we allow up to 120, we lint at 100 for readability.

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
